enum GithubEventType {
  commitCommentEvent,
  createEvent,
  deleteEvent,
  forkEvent,
  gollumEvent,
  issueCommentEvent,
  issuesEvent,
  memberEvent,
  publicEvent,
  pullRequestEvent,
  pullRequestReviewCommentEvent,
  pushEvent,
  releaseEvent,
  sponsorshipEvent,
  watchEvent,
}
