name: kyaru_bot
description: Kyaru is a waifu Telegram utility bot
version: 0.0.1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  dart_telegram_bot: ^0.5.1-beta.1
  dart_mongo_lite: ^0.1.0-beta.2
  http: ^0.13.1
  uuid: ^3.0.3
  image: ^3.0.2
  jiffy: ^4.1.0

dev_dependencies:
  effective_dart: ^1.3.1
