name: kyaru_bot
description: Kyaru is a waifu Telegram utility bot
version: 0.0.1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  dart_telegram_bot: ^0.4.1
  dart_mongo_lite: ^0.1.0-beta.2
  http: ^0.13.0
  uuid: ^3.0.1
  image: ^3.0.1
  jiffy: ^4.0.0
