name: kyaru_bot
description: Kyaru is a waifu Telegram utility bot
publish_to: none
version: 0.0.1

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  dart_telegram_bot: ^0.6.0
  dart_mongo_lite: ^0.1.1
  http: ^0.13.1
  uuid: ^3.0.3
  image: ^3.0.2
  jiffy: ^4.1.0
  logging: ^1.0.1
  html: ^0.15.0
  openweathermap: ^0.1.4

dev_dependencies:
  lints: ^1.0.1
